### ISSUE TITLE
Models?

### ISSUE THREAD

**Issue by Ryor97** [lilliepad1/buckshot-decomp-public#1]
where can the models be found? the "models" folder contains just the texture pngs. or are they part of "the files neccessary to compile the game"?

**Comment by uncreativeCultist** [comment]
Sorry for the month late response,
The models are imported into the Godot project, and thus, are only in the private repository.
Feel free to DM me on Discord for access to the private repository!

**Comment by Ryor97** [comment]
hey uhh so, about the models
i couldn't add you on discord so replying here.
i originally wanted to take a model or a few for a little something in a
different game, but currently i have some irl issues, and even if i get it
sorted out, i probably won't have motivation to do any of what i planned.

so i dont think i need these models anymore really.

чт, 4 апр. 2024 г., 22:28 lillie™ ***@***.***>:
