### ISSUE TITLE
I need offsets 

### ISSUE THREAD

**Issue by try57** [lilliepad1/buckshot-decomp-public#2]
where tf offsets at bro

apprec8 the release tho lit af

**Comment by uncreativeCultist** [comment]
I unfortunately don't have the offsets, as this project is mainly for decompiling the game to look at assets or to assist in the creation of mods for the game. If you're interested in doing the latter half, feel free to contact me on Discord and I'd be happy to give you the files needed to recompile the game. 

Assuming you're attempting to create a Cheat Engine Trainer (or something else of the sort,) there are tutorials online on how to find the offsets for the game yourself. If you'd like, I'd still be happy to give you the files needed to recompile the game if you think the files would help.

**Comment by asdwastakenig** [comment]
imagine getting caught

**Comment by uncreativeCultist** [comment]
i mean, to each their own. if he wants to cheat in a singleplayer game, go
for it. it's his own experience.

**Comment by asdwastakenig** [comment]
wait, why would someone cheat in a singleplayer game? just get good, the game is easy if luck is on your side

**Comment by uncreativeCultist** [comment]
i've done it with other games before, so i'm nobody to judge, but you're
right about the luck thing.

now that i think about it, i wonder if OP is trying to cheat the
leaderboards

**Comment by asdwastakenig** [comment]
alright

Am Sa., 13. Apr. 2024 um 18:20 Uhr schrieb lillie™ ***@***.***
